add node 16
TryGhost/node-sqlite3 pull request #1469
Opened 2021-06-01 11:10 UTC by DemianD

2021-06-14 06:10 UTC, mscdex commented on package.json
> +    "zeromq": "^5.2.8"
This seems unnecessary?

2021-06-14 06:10 UTC, mscdex commented on scripts/build_against_node.sh
> +    brew install zeromq
Ditto

2021-12-19 20:40 UTC, RocketFlashXD commented
is sqlite3 ever gonna be supported on node v16?

2022-03-01 12:44 UTC, UserJHansen requested changes
Try deleting the package-lock and all references to zeromq, it looks like it is causing compile issues

2022-04-12 20:41 UTC, daniellockyer commented
Hey @DemianD 👋🏻 Node 16 has been added to GitHub Actions CI and `sqlite3` should be able to compile on Node 16, or use the prebuilt binaries if they're available for your platform. 🙂 Given that, I'm going to close this PR 🙂

2022-04-12 20:41 UTC, closed without merging